### ISSUE TITLE
When feeding several prefixes to monitors, use temp json files

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#140]
**Is your feature request related to a problem? Please describe.**
Currently we may provide e.g., to bgpstreamlive/hist, as well as to betabmp very large lists of prefixes as command line arguments. Use json files instead for them.

**Describe the solution you'd like**
Temp json files that are erased after monitor has stopped.

N/A

**Additional context**
N/A

**Comment by slowr** [comment]
I freeze this because it might be difficult to move the monitors afterwards.

**Comment by vkotronis** [comment]
Problem that arised and led to this requirement:
```
root@0668b95058aa:/var/log/artemis# cat error.log 
__init__ - 2019-03-29 12:54:25,085 - ERROR @ wrapper: exception
Traceback (most recent call last):
  File "/root/core/utils/__init__.py", line 194, in wrapper
    return f(*args, **kwargs)
  File "/root/core/monitor.py", line 206, in init_ris_instances
    shell=False,
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/usr/local/bin/python3'
```

for configurations like:
```
prefixes:
    super_prefix: &super_prefix
        - 139.91.0.0/16
        - 139.0.0.0/8^24
```
