### ISSUE TITLE
Under large update load, duplicate errors may happen

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#155]
**Describe the bug**
```
postgres          | 2019-03-27 19:50:03.957 UTC [97] ERROR:  duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
postgres          | 2019-03-27 19:50:03.957 UTC [97] DETAIL:  Key ("timestamp", key)=(2019-03-27 18:51:16, 5b493bfce84793005b65fa2dde81bd0f) already exists.
postgres          | 2019-03-27 19:50:03.957 UTC [97] STATEMENT:  INSERT INTO bgp_updates (prefix, key, origin_as, peer_asn, as_path, service, type, communities, timestamp, hijack_key, handled, matched_prefix, orig_path) VALUES ('139.71.152.0/22','5b493bfce84793005b65fa2dde81bd0f',6307,38726,ARRAY[38726,9957,3491,701,6307],'bgpstream|routeviews|route-views4','A','[[3491, 2004], [3491, 2000]]','2019-03-27T18:51:16'::timestamp,'{}',false,('139.0.0.0/8'),'null'),('139.71.152.0/22','b52426663a6d1690045f6adde5153171',6307,134708,ARRAY[134708,9902,3491,7018,6307],'bgpstream|routeviews|route-views3','A','[]','2019-03-27T18:51:19.574358'::timestamp,'{}',false,('139.0.0.0/8'),'null')
backend           | database - 2019-03-27 19:50:03,958 - ERROR @ _insert_bgp_updates: exception
backend           | Traceback (most recent call last):
backend           |   File "/root/core/database.py", line 1038, in _insert_bgp_updates
backend           |     db_cur, query, self.insert_bgp_entries, page_size=1000
backend           |   File "/usr/local/lib/python3.6/site-packages/psycopg2/extras.py", line 1278, in execute_values
backend           |     cur.execute(b''.join(parts))
backend           | psycopg2.IntegrityError: duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2019-03-27 18:51:16, 5b493bfce84793005b65fa2dde81bd0f) already exists.
```

**Affected Component(s)**
- [x] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**

**Expected behavior**
Need to make sure that redis is bootstrapped with the bgp update keys of the last 2 hours.

**Screenshots**

**System (please complete the following information):**

**Additional context**

**Comment by vkotronis** [comment]
Update: need to bootstrap redis with the bgp update keys of the last 2 hours on startup!
