### ISSUE TITLE
Investigate stuck detection (not handling incoming updates) transient bug

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#564]
**Describe the bug**
Sometimes (it is hard to replicate since not consistent), detection may get stuck and its data worker(s) cannot restart. This is because the detection-related RMQ queues vanish (are deleted).
May be related to the RMQ worker consumers getting stuck by specific messages which I could not identify.

**Affected Component(s)**
- [X] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**
It is manifested in https://demo.bgpartemis.org/ after some time. I cannot understand what gets stuck actually, but the detection does not handle new messages. Related queues vanish from the broker.

**Expected behavior**
All messages should be eventually handled as long as detection is active.

**Screenshots**
![Screenshot_2021-01-10 ARTEMIS - Overview](https://user-images.githubusercontent.com/1815007/104122699-37493b00-534f-11eb-8c95-903076f8ebac.png)

**System (please complete the following information):**
```docker-compose -f docker-compose.yaml -f docker-compose.routinator.yaml up --scale detection=4 --scale prefixtree=4 --scale database=4 -d```
+ default configuration

**Additional context**
Workaround: 
```
docker-compose restart detection
```
restores all detection queues and reinstates proper expected behavior.

**Comment by vkotronis** [comment]
Closing since I could not replicate in deployment. Was probably sth transient with RMQ (maybe a corrupt image). Will re-open if re-observed.

**Comment by vkotronis** [comment]
re-opening since I observed that in the demo deployment.
@slowr when available let me know to take a look at it, I will try to pinpoint what/why is stuck (I cannot replicate it always, it is random).
![Uploading Screenshot_2021-01-14 ARTEMIS - BGP Updates.png…]()

**Comment by vkotronis** [comment]
At first view the REST API seems to work perfectly, what gets stuck is one of the RMQ handlers. I have difficulty identifying exactly which one though, since I do not see any related errors detection-wise.

Temporary work-around when this happens:
```
docker-compose restart detection
```

Need a way to find out exactly where the deployed detection consumers/handlers get stuck so that we do not have to restart the container when this happens.

**Comment by vkotronis** [comment]
This might be unrelated but I document it just in case here (client-side error due to server-side malformed message)
```
riperistap_1         | ripe_ris - 2021-01-14 14:13:51,455 - ERROR @ run: exception
riperistap_1         | Traceback (most recent call last):
riperistap_1         |   File "/root/core/ripe_ris.py", line 431, in run
riperistap_1         |     msg, prefix_tree
riperistap_1         |   File "/root/core/ripe_ris.py", line 552, in normalize_ripe_ris
riperistap_1         |     for prefix in prefixes:
riperistap_1         | ValueError: Invalid key type
riperistap_1         | ripe_ris - 2021-01-14 14:13:51,457 - ERROR @ run: exception message b'{"type":"ris_message","data":{"timestamp":1610632822.05,"peer":"195.66.224.159","peer_asn":"8966","id":"01-195-66-224-159-1167377","host":"rrc01","type":"UPDATE","announcements":[{"next_hop":"null","prefixes":["eor"]}],"raw":"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00170200000000"}}'
```

**Comment by vkotronis** [comment]
Moving to next minor release 2.1.0 to make sure that we can replicate correctly in user envs (if it is an actual problem).

**Comment by vkotronis** [comment]
closing since not replicable. Will re-open if needed.
